stages:
  - generate
  - deploy

generate-job:
  stage: generate
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
